# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-23 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('complaintid', models.IntegerField(primary_key=True, serialize=False)),
                ('rollno', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('complaint', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staffid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('hostel', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('rollno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('hostel', models.CharField(max_length=100)),
                ('roomno', models.IntegerField()),
                ('program', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('fathername', models.CharField(max_length=100)),
                ('mothername', models.CharField(max_length=100)),
                ('fatherocc', models.CharField(max_length=100)),
                ('motherocc', models.CharField(max_length=100)),
                ('guardianname', models.CharField(max_length=100)),
                ('guardianocc', models.CharField(max_length=100)),
                ('localaddress', models.CharField(max_length=100)),
                ('permanentaddress', models.CharField(max_length=100)),
                ('accountno', models.BigIntegerField()),
                ('bankname', models.CharField(max_length=100)),
                ('branchname', models.CharField(max_length=100)),
                ('ifsccode', models.CharField(max_length=100)),
                ('mobileno', models.BigIntegerField()),
                ('parentcntctno', models.BigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='complaints',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Student'),
        ),
    ]
