# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-23 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nb1', models.CharField(max_length=100)),
                ('nb2', models.CharField(max_length=100)),
                ('nb3', models.CharField(max_length=100)),
                ('nb4', models.CharField(max_length=100)),
                ('nb5', models.CharField(max_length=100)),
                ('rv1', models.CharField(max_length=100)),
                ('rv2', models.CharField(max_length=100)),
                ('rv3', models.CharField(max_length=100)),
                ('rv4', models.CharField(max_length=100)),
                ('rv5', models.CharField(max_length=100)),
                ('uv1', models.CharField(max_length=100)),
                ('uv2', models.CharField(max_length=100)),
                ('uv3', models.CharField(max_length=100)),
                ('uv4', models.CharField(max_length=100)),
                ('uv5', models.CharField(max_length=100)),
            ],
        ),
    ]
