from django.db import models

# Create your models here.

class Student(models.Model):
    rollno = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=100)
    hostel = models.CharField(max_length=100)
    roomno = models.IntegerField()
    program = models.CharField(max_length=100)
    department = models.CharField(max_length=100)
    email = models.EmailField()
    password = models.CharField(max_length=100)
    fathername = models.CharField(max_length=100)
    mothername = models.CharField(max_length=100)
    fatherocc = models.CharField(max_length=100)
    motherocc = models.CharField(max_length=100)
    guardianname = models.CharField(max_length=100)
    guardianocc = models.CharField(max_length=100)
    localaddress = models.CharField(max_length=100)
    permanentaddress = models.CharField(max_length=100)
    accountno = models.BigIntegerField()
    bankname = models.CharField(max_length=100)
    branchname = models.CharField(max_length=100)
    ifsccode = models.CharField(max_length=100)
    mobileno = models.BigIntegerField()
    parentcntctno = models.BigIntegerField()

class Complaint(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    complaintid = models.IntegerField(primary_key=True)
    rollno = models.IntegerField()
    type = models.CharField(max_length=100)
    complaint = models.CharField(max_length=100)
    time = models.DateTimeField()

class Staff(models.Model):
    staffid = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=100)
    designation = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    hostel = models.CharField(max_length=100)
    email = models.EmailField()
class Hostel(models.Model):
    name = models.CharField(max_length=100)
    nb1 = models.CharField(max_length=100)
    nb2 = models.CharField(max_length=100)
    nb3 = models.CharField(max_length=100)
    nb4 = models.CharField(max_length=100)
    nb5 = models.CharField(max_length=100)
    rv1 = models.CharField(max_length=100)
    rv2 = models.CharField(max_length=100)
    rv3 = models.CharField(max_length=100)
    rv4 = models.CharField(max_length=100)
    rv5 = models.CharField(max_length=100)
    uv1 = models.CharField(max_length=100)
    uv2 = models.CharField(max_length=100)
    uv3 = models.CharField(max_length=100)
    uv4 = models.CharField(max_length=100)
    uv5 = models.CharField(max_length=100)